### ISSUE TITLE
Theme outdated on the BetterDiscord site, still uses the old import.

### ISSUE THREAD

**Issue by ghost** [RockESV/Eris#10]
If you could fix that at the soonest possible convenient time for you that'd be appreciated.  Otherwise you will need to resubmit the theme after it's removed.

**Comment by RockESV** [comment]
Hello! This was actually an issue with the GitHub Pages deployment of the source files, it was not working properly so the CSS import wouldn't work, either. Thank you for bringing this to my attention!
