### ISSUE TITLE
Some headers defaulting to Times New Roman(?) after Discord's "gg sans" update.

### ISSUE THREAD

**Issue by hanakomisa** [RockESV/Eris#4]
![image](https://user-images.githubusercontent.com/32932571/205146080-8b527522-caae-46f9-950c-29d45bbb1dbf.png)
![image](https://user-images.githubusercontent.com/32932571/205145575-6dd59dff-195f-457d-af7e-916c9a860cda.png)

As seen here, multiple places doesn't use the new font that Discord has dropped today.
Confirmed reproduce-able on Discord Stable 161678 + BetterDiscord 1.8.2/Vencord daf3a1d (Client/Web) / ArmCord 1.3.0 + VenCord daf3a1d.
(edit: accidentally left tag in one of the screenshots.)

**Comment by RockESV** [comment]
Thank you for reporting this! Sorry it's been taking a while to roll out fixes, I've been super busy with school the past week. Since Discord has removed the Whitney font from their assets altogether, I've simply added it as part of the Eris local files:
```
@font-face {
    font-family: 'Whitney';
    font-style: normal;
    font-weight: 300;
    src: url(https://rockesv.github.io/Eris/Resources/Fonts/whitney-normal-300.woff2) format("woff2");
}
@font-face {
    font-family: 'Whitney';
    font-style: italic;
    font-weight: 300;
    src: url(https://rockesv.github.io/Eris/Resources/Fonts/whitney-italic-300.woff2) format("woff2");
}
@font-face {
    font-family: 'Whitney';
    font-style: normal;
    font-weight: 400;
    src: url(https://rockesv.github.io/Eris/Resources/Fonts/whitney-normal-400.woff2) format("woff2");
}
@font-face {
    font-family: 'Whitney';
    font-style: italic;
    font-weight: 400;
    src: url(https://rockesv.github.io/Eris/Resources/Fonts/whitney-italic-400.woff2) format("woff2");
}
@font-face {
    font-family: 'Whitney';
    font-style: normal;
    font-weight: 500;
    src: url(https://rockesv.github.io/Eris/Resources/Fonts/whitney-normal-500.woff2) format("woff2");
}
@font-face {
    font-family: 'Whitney';
    font-style: italic;
    font-weight: 500;
    src: url(https://rockesv.github.io/Eris/Resources/Fonts/whitney-italic-500.woff2) format("woff2");
}
@font-face {
    font-family: 'Whitney';
    font-style: normal;
    font-weight: 600;
    src: url(https://rockesv.github.io/Eris/Resources/Fonts/whitney-normal-600.woff2) format("woff2");
}
@font-face {
    font-family: 'Whitney';
    font-style: italic;
    font-weight: 600;
    src: url(https://rockesv.github.io/Eris/Resources/Fonts/whitney-italic-600.woff2) format("woff2");
}
@font-face {
    font-family: 'Whitney';
    font-style: normal;
    font-weight: 700;
    src: url(https://rockesv.github.io/Eris/Resources/Fonts/whitney-normal-700.woff2) format("woff2");
}@font-face {
    font-family: 'Whitney';
    font-style: italic;
    font-weight: 700;
    src: url(https://rockesv.github.io/Eris/Resources/Fonts/whitney-italic-700.woff2) format("woff2");
}

:root {
    --font-primary: 'Whitney' !important;
    --font-display: 'Whitney' !important;
}
```

This should fix the issue and safeguard Eris from any future font change. I'm not using the new "gg sans" font because, frankly, it looks awful. I am planning, though, to implement some customization options for Eris in the future, including fonts and colors.

Thanks again for the report!

**Comment by hanakomisa** [comment]
Thank you for fixing it (I noticed and closed the issue then) and also giving us our old beloved Whitney back! Was an absolute delight when I opened up Discord today and saw Whitney as my font again.
