### ISSUE TITLE
Cant show names

### ISSUE THREAD

**Issue by kyoshhz** [RockESV/Eris#5]
Cant show plugins and themes names 
![plugin](https://user-images.githubusercontent.com/35954455/232411636-7d118cd8-34c6-4130-a448-4f1b3dc61486.JPG)
![themes](https://user-images.githubusercontent.com/35954455/232411646-9da8c98e-4ccf-4f16-ad69-e3d9db03fed4.JPG)

**Comment by RockESV** [comment]
I can't seem to replicate this issue. What plugins are you using?

![image](https://github.com/RockESV/Eris/assets/86799620/68e578b5-0e3b-4933-9582-9efbb7c097d3)

**Comment by kyoshhz** [comment]
i import mini addon custom css i thinks thats why cuz i remove the import link everything works normally

**Comment by kyoshhz** [comment]
source [mini addon](http://maendisease.github.io/BetterDiscordStuff/css/bdAddonMini.css)
